#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

# License (BSD-3-clause)
# ======================
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# - Neither the name of the Martin Ueding nor the names of his contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""
unwrap PDF into JPEG files
==========================

This converts a PDF file into the JPEG files it was made out of initially and
numbers them with a ``+1``, ``+2``, ... scheme.

Basically, it is just a simple wrapper for ``pdfimages -j`` since I do not like
its numbering scheme.

usage
-----

Call with multiple files::

    unwrap-pdf-to-jpeg file.pdf other.pdf third.pdf

And you will end up with::

    file+1.jpg
    file+2.jpg
    file+3.jpg
    ...
    file+8.jpg

    other+01.jpg
    ...
    other+87.jpg

    third+1.jpg
    third+2.jpg
"""

import glob
import optparse
import os
import shutil
import subprocess
import uuid

__docformat__ = "restructuredtext en"

def main():
    options, args = _parse_args()

    for infile in args:
        ident = str(uuid.uuid4())

        status = subprocess.call(["pdfimages", "-j", infile, ident])
        print "Status", status

        if status != 0:
            continue

        files = sorted(glob.glob(ident+"-*"))
        print "Files", files
        count = len(files)
        print "Count", count
        digits = len(str(count))
        print "Digits", digits

        success = True

        for i, f in zip(xrange(1, count+1), files):
            if not f.endswith(".jpg"):
                print "No JPEG generated, deleting ..."
                os.remove(f)
                success = False
            else:
                formatter = "%0"+str(digits)+"d"
                new_name = infile[:-4]+"+"+(formatter % i)+".jpg"
                print "->", f, new_name
                os.rename(f, new_name)

        if success:
            trashfile = os.path.expanduser("~/.local/share/Trash/files/")
            print "Trashfile", trashfile
            shutil.move(infile, trashfile)

def _parse_args():
    """
    Parses the command line arguments.

    :return: Tuple with options and (positional) arguments.
    :rtype: tuple
    """
    parser = optparse.OptionParser(usage="", description="")

    return parser.parse_args()

if __name__ == "__main__":
    main()
