#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

"""
Goes through the directory structure, searches for multiple JPEG images which
are named with the ``+1``, ``+2``, … scheme and uses ``convert`` to create a
PDF with all the images in correct order.
"""

import argparse
import os.path
import re
import shutil
import subprocess

__docformat__ = "restructuredtext en"

srcdir = os.path.expanduser("~/PDF_Source")

def create_srcdir():
    if not os.path.isdir(srcdir):
        os.mkdir(srcdir)


def main():
    options = _parse_args()

    plus_pattern = re.compile(r"([^+]+)(\+\d+)(\.jpg)")

    for root, dirs, files in os.walk("."):
        jpegs = {}
        for file in files:
            m = plus_pattern.match(file)
            if m is None:
                continue
            
            prefix = (root, m.group(1))
            suffix = (m.group(2), m.group(3))
            if not prefix in jpegs:
                jpegs[prefix] = []

            jpegs[prefix].append(suffix)

        for key in jpegs:
            jpegs[key].sort()

        if len(jpegs) > 0:
            for prefix in jpegs:
                images = []
                for suffix in jpegs[prefix]:
                    images.append(os.path.join(prefix[0], prefix[1]+suffix[0]+suffix[1]))

                pdf_file = os.path.join(prefix[0], prefix[1]+".pdf")

                call = ["convert"]+images+[pdf_file]
                print ' '.join(call)
                subprocess.check_call(call)

                create_srcdir()

                for image in images:
                    shutil.move(image, os.path.join(srcdir, os.path.basename(image)))


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="", description="")
    parser.add_argument('args', metavar='N', type=str, nargs='*',
                   help='Positional arguments.')
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument('--version', action='version', version='<the version>')

    return parser.parse_args()


if __name__ == "__main__":
    main()
